insert into r_enum_value values ('service_type',1,'NONE','NONE');
insert into r_enum_value values ('service_type',2,'TV','Comvenient');
insert into r_enum_value values ('service_type',3,'BB','Packetspan');
insert into r_enum_value values ('service_type',4,'IPTV','Stalker');
alter table b_process_request_detail add column `service_type` varchar(25) default null;
alter table b_ippool_details add column notes varchar(60);
alter table b_ippool_details add column `type` char(1);
alter table b_bill_master add column group_id bigint(20) DEFAULT NULL;
alter table b_prov_service_details add column `category` varchar(20) DEFAULT NULL;
alter table b_prov_service_details add column `sub_category` varchar(20) DEFAULT NULL;
update m_client set group_name=null;
alter TABLE m_client add column is_indororp varchar(3) default null;
alter table m_client change group_name group_id bigint(10) default null;
alter table m_client add column exempt_tax char(1) DEFAULT 'N';
alter table m_client add column bill_mode varchar(10) DEFAULT NULL;
